### ISSUE TITLE
Weird issue with modal if the `body` has no classes

### ISSUE THREAD

**Issue by rockwellll** [excid3/tailwindcss-stimulus-components#136]
So. I was in the process of upgrading both tailwind and this package. After upgrading i found out that on pages where the `body` tag has no classes attached to it the modal would "push" the elements of the page into the left side. But, if i just add the a "class" to the body tag it stops doing this.
 
https://user-images.githubusercontent.com/38360603/152149855-c7314f56-c973-4098-ba34-2c6821225dff.mov

I think it might have to do with this but not quite sure yet.

https://github.com/excid3/tailwindcss-stimulus-components/blob/5e138ab83828ec6f49afc485826ead7ba89ab8a9/src/modal.js#L126

**Comment by elalemanyo** [comment]
@rockwellll I was having the same issue, and your fix worked perfectly, thanks!
That's why I felt free to open a [pull request](https://github.com/excid3/tailwindcss-stimulus-components/pull/161), I hope you don't mind. If you can take a look at it and let me know what you think, would be great 🙂

Thanks!

**Comment by rockwellll** [comment]
Hey @elalemanyo. Glad it helped you out.

No worries. I'm glad you turned in into a PR. 

The changes you've made are outstanding. I like the fact you extracted the classes into a value so that it can be overriden easily. 

Fantastic job!.

**Comment by jaywhy** [comment]
@rockwellll, I hit a similar issue today, but I believe your issue and mine are related to tailwind not picking up all the class names required by the modal component.

I think what is at issue is `inset-x-0` not being compiled. I'm guessing the point of setting body to `fixed` is to get rid of scrollbars, but without `inset-x-0`, the content will shrink.

The fix is to add all or part of the component js files to the content sources. 

```
module.exports = {
  content: [
    //...
    './node_modules/tailwindcss-stimulus-components/src/*.js'
  ]
}
```

Here is an example of the [issue](https://play.tailwindcss.com/tuks6YmcwL).

**Comment by SalvesTestservices** [comment]
When I apply the solution of @jaywhy it solves the issue, but then I get kind of dark gray layer on top of everything which also blocks the modal:

![issue](https://user-images.githubusercontent.com/7660996/214791022-e4a737e3-731c-4025-a317-cc15e63bcff8.png)

When I remove the line from tailwind config, this blocking layer is gone (but the original issue is back):

![issue2](https://user-images.githubusercontent.com/7660996/214791173-69506657-6b00-4782-9ae1-6bf82894ad09.png)

**Comment by HashNuke** [comment]
Before attempting @jaywhy's solution , I fixed it by adding `w-full` class to the body. That would fix this issue.

But the solution that @jaywhy mentioned in his comment is the right way to fix this. (I can confirm that fixed the issue too).

If you are only using the modal component, make sure to only include the `modal.js` file in the tailwind config (like below).

```js
module.exports = {
  content: [
    //...
    './node_modules/tailwindcss-stimulus-components/src/modal.js'
  ]
}
```

I think we can close this ticket.

**Comment by excid3** [comment]
Modals now use the `<dialog>` html element so they're simpler to style now.
