### ISSUE TITLE
Google Chrome Autofill Result Select Causes Modal Close

### ISSUE THREAD

**Issue by Petercopter** [excid3/tailwindcss-stimulus-components#207]
If you have a form inside a Modal component, and you select a result from Google Chrome autofill, it causes the modal to close.

Using the example https://github.com/excid3/tailwindcss-stimulus-components/blob/master/docs/modal.md#usage

```
<div data-controller="modal" data-action="keydown.esc->modal#close" tabindex="-1" class="relative z-10">
```
This is the problem right here:
```
data-action="keydown.esc->modal#close"
```
I am 99% sure this is something new. We've had forms in modals for months, and this is the first time I'm seeing it.

The first time I noticed it (today) was because we have a user profile in a modal. When you open the modal, it immediately closes because the password is being autofilled, causing the modal to close.

**Comment by solilin** [comment]
I have the same problem

**Comment by excid3** [comment]
This should be fixed now that we've moved to the `<dialog>` element.

**Comment by noahhaon** [comment]
Hello, just a comment here for anyone else that runs into this.

Removing the `data-action="keydown.esc->modal#close"` attribute on the enclosing element(s) prevents the issue, and the user is still able to close the modal with `esc` since it now must be enclosed in a `dialog` element which handles this event properly.
