### ISSUE TITLE
jsfiddle demo is broken

### ISSUE THREAD

**Issue by bbugh** [excid3/tailwindcss-stimulus-components#36]
"Uncaught ReferenceError: TailwindcssStimulusComponents is not defined"

https://jsfiddle.net/excid3/176obwmc/

**Comment by excid3** [comment]
Thanks for the heads up @bbugh. I think that's because of the recent changes we did for the builds. 

@adrienpoly do you have any tips on fixing this? I am going to remove the jsfiddle, but the docs/index.html file in the repo is the one I want to fix. Tried switching to the UMD file but the `import { Controller } from "stimulus"` doesn't actually grab that. I don't know this well enough yet.

**Comment by adrienpoly** [comment]
@excid3 i am currently on my phone hard to tell like this. I can look into it a bit later

**Comment by excid3** [comment]
No rush! Whenever you get the chance would be awesome. I'm going to try reading up and seeing what's up. 

One thing I noticed is the UMD module is defining `tailwindcssStimulusComponents` instead of `TailwindcssStimulusComponents`, but after it defines that, it fails to grab the Controller from the Stimulus module, so something to do with grabbing that from the Stimulus UMD I guess.

**Comment by adrienpoly** [comment]
I am not very familiar with JSfiddle and UMD 

At first I copied the demo to a codesandbox using typical imports etc 
https://codesandbox.io/s/tailwindcss-stimulus-components-demo-p39j7?file=/index.js

This is working but the issues I think remains alive for using this package without a bundler and doing the usual import things

I ll try to see what I can find

**Comment by adrienpoly** [comment]
I think I have the solution

Ok by default microbundle generates a UMD module name with the camelCase of the package
this can be overwritten with additing this in the package.json

`"amdName": "TailwindcssStimulusComponents",` 
source https://github.com/developit/microbundle#-usage--configuration-

This should solve the naming part of the UMD module but what was strange is that looking into the current `tailwindcssStimulusComponents` module it was present but empty....

It looks like in the module it is missing the `Stimulus` module and therefore the package crash and export an empty package

I have quickly tested a solution that I think works by adding an option to the build script

`"build": "microbundle --globals stimulus=Stimulus",` 

I don't have time to write a formal PR but hopefully this should help



So I am not sure this would

**Comment by excid3** [comment]
You're the best @adrienpoly! It totally skipped my mind yesterday that this would be because of changing Stimulus to a peer dependency.

It seems like the `--external` option should work since it's supposedly for peerDependencies, but I couldn't get it to work, so I've used the globals for now like you mentioned. Also fixed the package name.

**Comment by excid3** [comment]
@bbugh I should note, I'm getting rid of the JSFiddle and just going to use the docs page from now on:

http://excid3.github.io/tailwindcss-stimulus-components
