### ISSUE TITLE
Multiple modals

### ISSUE THREAD

**Issue by jbutkowski** [excid3/tailwindcss-stimulus-components#61]
Documentation isn't clear about how to implement multiple modals on the same page - can you please clarify?

**Comment by jbutkowski** [comment]
Never mind, I figured it out.

**Comment by SamuelAierizer** [comment]
Would someone share their solution?

**Comment by SamuelAierizer** [comment]
For someone who may be searching for this, here is how I solved it. It is not very elegant, but for the moment it does the job.

Inside the modal.js file I changed the open(e) function. In stimulus 3 we have action params, so I used those to pass an id value of the modal I wanted to show. If no value is passed, then the existing functionality should remain. If a select value was passed, then I grab the element by the id and display it. 
```
    // Unhide the modal
    let selectedModal = e.params.select;
    if (selectedModal === void 0) {
      this.containerTarget.classList.remove(this.toggleClass);
    } else {
      document.getElementById(selectedModal).classList.remove(this.toggleClass);
    }
```

The same was used in the close(e) function but adding to the classList instead of removing. 


All you need to do is provide the data-model-select-param="modal1" for all data-actions that are for that modal and of course give your data-model-target="container" div the id="modal1".
